
<ul class="nav navbar-nav">

    <?php $count = -1; ?>
    <?php // find the end of the menu ?>
    <?php $maxDepth = count($this->container) - 1; ?>
    <?php foreach ($this->container as $key => $page): ?>
        <?php $count++; ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php // when using partials we need to manually check for ACL conditions ?>
        <?php if( ! $page->isVisible() || !$this->uthandoNavigation()->accept($page)) continue; ?>
        <?php $isActive = $page->isActive(true); ?>
        <?php $hasChildren = (($page->rgt - $page->lft) - 1) / 2; ?>

        <?php if ($hasChildren): ?>
            <?php $submenu = ($page->depth > 0) ? '-submenu': ''; ?>
            <li class="dropdown<?=$submenu; ?><?php if ($isActive) echo ' active'; ?>">
                <a id="drop<?=$count ?>" href="#" class="dropdown-toggle" data-toggle="dropdown">
            	   <span><?=$page->getLabel() ?></span>
            	   <?php if ($page->depth == 0): ?>
            	   <b class="caret"></b>
            	   <?php endif; ?>
                </a>
            <ul class="dropdown-menu">
        <?php elseif ($page->depth > 0): ?>
                <li class="<?php if ($isActive) echo 'active'; ?>">
                    <a tabindex="-1" href="<?=$page->getHref() ?>">
                        <?=$page->getLabel() ?>
                    </a>
        <?php else: ?>
        <li class="<?php if ($isActive) echo 'active'; ?>">
            <a href="<?=$page->getHref() ?>">
            	<?php if (strtolower($page->getLabel()) === 'home'): ?>
            		<i class="icon-home"></i>
            	<?php else: ?>
                	<?=$page->getLabel() ?>
                <?php endif; ?>
            </a>
        <?php endif; ?>
        
        <?php // closures ?>
        
        <?php if ($page->depth > 0): ?>

            <?php if ($count == $maxDepth): ?>
                <?=str_repeat('</li></ul>', $page->depth); ?>
			</li>
            <?php elseif ($arrayCopy[$count + 1]['depth'] < $page->depth): ?>
                <?=str_repeat('</li></ul>', ($page->depth - $arrayCopy[$count + 1]['depth'])); ?>
			</li>
			<?php else: ?>
            </li>
            <?php endif; ?>
        <?php else: ?>
        </li>
        <?php if (strtolower($page->getLabel()) === 'home'): ?>
		<li class="divider-vertical"></li>
		<?php endif; ?>
        <?php endif; ?>
    <?php endforeach ?>
</ul>
