language: php

php:
  - 7.0
  - 7.1

before_script:
  - cd ..
  - git clone git://github.com/uthando-cms/uthando.git
  - git clone git://github.com/uthando-cms/uthando-common.git
  - git clone git://github.com/uthando-cms/uthando-user.git
  - cd uthando
  - composer install
  - cp -R ../uthando-navigation ./module/UthandoNavigation
  - cp -R ../uthando-common ./module/UthandoCommon
  - cp -R ../uthando-user ./module/UthandoUser
  - cd module/UthandoNavigation/test

script:
  - phpdbg -qrr ../../../vendor/bin/phpunit -v

after_script:
  - cd ../
  - cp -R ../../vendor ./vendor
  - php vendor/bin/test-reporter --coverage-report=build/logs/clover.xml
