language: php

php:
  - 5.5
  - 5.6

before_script:
  - cd ..
  - git clone git://github.com/uthando-cms/uthando.git
  - git clone git://github.com/uthando-cms/uthando-common.git
  - git clone git://github.com/uthando-cms/uthando-user.git
  - cd uthando
  - composer install
  - cp -R ../uthando-navigation ./module/UthandoNavigation
  - cp -R ../uthando-common ./module/UthandoCommon
  - cp -R ../uthando-user ./module/UthandoUser
  - cd module/UthandoNavigation/test

script:
  - phpunit

after_script:
  - cd ../../../
  - php vendor/bin/test-reporter --coverage-report=build/logs/clover-UthandoNavigation.xml
