<?php
$routeParams = (is_array($this->routeParams)) ? $this->routeParams : [];
$form = $this->form;
$routeArray = ['action' => $this->formAction];
if (isset($this->primaryKey)) $routeArray['id'] = $this->primaryKey;
$form->get('menuId')->setValue($this->menuId);
?>
<div class="row">
	<form class="col-md-12 form-horizontal" method="post" action="<?=$this->url($this->postRoute, array_merge($routeParams, $routeArray)) ?>">
		<fieldset>
			<legend><?=ucwords($this->formAction); ?> <?=$this->formName;?> Form:</legend>
			<div class="row">
                <div class="col-md-6">
                    <?php foreach($this->formElements as $element):?>
                    <?php if ($form->get($element)->getAttribute('type') != 'hidden'):?>
                    <div class="form-group<?php if ($form->get($element)->getMessages()) echo ' has-error'; ?>">
                        <label class="col-md-4 control-label" for="title"><?=$form->get($element)->getLabel();?></label>
                        <div class="col-md-8">
                            <?=$this->formelement($form->get($element)->setAttribute('class', 'form-control')); ?>
                            <span class="help-block">
                            <?=$this->formElementErrors($form->get($element), [
                                'class' => 'list-unstyled'
                            ]); ?>
                            </span>
                        </div>
                    </div>
                    <?php else: ?>
                    <?=$this->formelement($form->get($element)); ?>
                    <?php endif;?>
                    <?php endforeach;?>
                    <input type="hidden" name="action" value="<?=$this->formAction;?>">
                </div>
                
                <div class="col-md-6">
                    <div class="form-group<?php if ($form->get('position')->getMessages()) echo ' has-error'; ?>">
                        <label class="col-md-4 control-label" for="title"><?=$form->get('position')->getLabel();?></label>
                        <div class="col-md-8">
                            <?=$this->formElement($this->form->get('position')->setMenuId($this->menuId)->setAttribute('class', 'form-control')); ?>
                            <span class="help-block">
                            <?=$this->formElementErrors($form->get('position'), [
                                'class' => 'list-unstyled'
                            ]); ?>
                            </span>
                            <label class="radio">
                                <input type="radio" name="menuInsertType" id="menuInsertType1" value="insert" checked>
                                insert after this page.
                            </label>
                            <label class="radio">
                                <input type="radio" name="menuInsertType" id="menuInsertType2" value="insertSub">
                                insert as a subpage of this page.
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary" data-loading-text="Please wait...">
                	Submit
                </button>
                <button type="button" class="btn btn-warning"  data-loading-text="Please wait..." onClick="window.location = '<?=$this->url($this->cancelRoute, array_merge($routeParams, $routeArray));?>';">
                	Cancel
                </button>
            </div>
        </div>
		</fieldset>
	</form>
</div>
