<?php
$routeParams = (is_array($this->routeParams)) ? $this->routeParams : [];
$form = $this->form;
$routeArray = ['action' => $this->formAction];
if (isset($this->primaryKey)) $routeArray['id'] = $this->primaryKey;
$form->get('menuId')->setValue($this->menuId);
?>
<div>
	<form class="form form-horizontal" method="post" action="<?=$this->url($this->postRoute, array_merge($routeParams, $routeArray)) ?>">
		<fieldset>
			<legend><?=ucwords($this->formAction); ?> <?=$this->formName;?> Form:</legend>
			<div class="row">
                <div class="span6">
                    <?php foreach($this->formElements as $element):?>
                    <?=$this->ztbFormElement($form->get($element));?>
                    <?php endforeach;?>
                    <input type="hidden" name="action" value="<?=$this->formAction;?>">
                </div>
                <div class="span6">
           	        <?=$this->ztbFormElement($form->getMenuItemSelect($this->menuId)); ?>
           	        <div class="control-group">
                        <div class="controls">
                       	    <label class="radio">
                                <input type="radio" name="menuInsertType" id="menuInsertType1" value="insert" checked>
                                insert after this page.
                            </label>
                            <label class="radio">
                                <input type="radio" name="menuInsertType" id="menuInsertType2" value="insertSub">
                                insert as a subpage of this page.
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn btn-primary" data-loading-text="Please wait...">
                	Submit
                </button>
                <button type="button" class="btn btn-warning"  data-loading-text="Please wait..." onClick="window.location = '<?=$this->url($this->cancelRoute, array_merge($routeParams, $routeArray));?>';">
                	Cancel
                </button>
            </div>
        </div>
		</fieldset>
	</form>
</div>