<?php $this->headTitle('Add Menu Item') ?>
<?php $this->layout()->pageTitle = $this->translate('Add Menu Item');?>

<?php $this->placeholder('header-buttons')->captureStart();?>
<button type="submit" form="form-menu-item" data-toggle="tooltip" title="<?=$this->translate('Save');?>" class="btn btn-primary">
    <i class="fa fa-save"></i>
</button>
<a href="<?=$this->url('admin/menu-item');?>" data-toggle="tooltip" title="<?=$this->translate('Cancel');?>" class="btn btn-default">
    <i class="fa fa-reply"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<?php

$this->form->get('menuId')->setValue($this->routeParams['menuId']);

$this->form->setAttributes([
    'method' => 'post',
    'id' => 'form-menu-item',
    'action' => $this->url('admin/menu-item/edit', [
        'menuId' => $this->routeParams['menuId'],
        'action' => 'add',
    ]),
]);

?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i> <?=$this->translate('Add Menu Item');?></h3>
    </div>
    <div class="panel-body">
        <?=$this->form($this->form);?>
    </div>
</div>

