
<?=$this->partial('uthando-admin/partial/search', [
	'name'			=> 'menuItem',
	'searchInputs'	=> [
		'Menu Item' => 'menuItemId',
	],
    'excludeMenu'   => true,
]);?>

<p>
    <a href="<?=$this->url('admin/menu-item/edit', [
        'menuId' => $this->menuId,
        'action' => 'add',
    ]); ?>" class="btn btn-default">Add Menu Item</a>
</p>


<div id="table-menuItem">
	<?=$this->partial('uthando-navigation/menu-item/list', [
	    'models' => $this->models,
	    'menuId' => $this->menuId,
	]); ?>
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(document).ready(function(){
	$('#table-menuItem').dataGrid({
    	url : '<?=$this->menuId?>/list',
    	query: { sort : 'name' },
    	searchForm : $('#search-menuItem'),
    	paging : 'links',
    	columnSort: true
	});
});
<?php $this->inlineScript()->captureEnd(); ?>
