<?php $this->headTitle('Pages') ?>

<?php if (count($this->models) > 0): ?>

<table class="table table-hover table-bordered table-condensed">
	<thead>
		<tr>
			<th data-field="menuItemId">Menu Item Id</th>
			<th data-field="label">Label</th>
			<th data-field="params">Params</th>
			<th data-field="route">Route</th>
			<th data-field="reource">Resource</th>
			<th data-field="isVisible">Is Visible</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->models as $row): ?>
		<tr>
			<td><?php echo $this->escapeHtml($row->getMenuItemId()); ?></td>
			<td>
                <?php echo str_repeat('&nbsp;&nbsp;', ($row->getDepth())) . '&bull;&nbsp;'; ?>
                <?php echo $this->escapeHtml($row->getLabel()); ?></td>
			<td><?php echo $this->escapeHtml($row->getParams()); ?></td>
			<td><?php echo $this->escapeHtml($row->getRoute()); ?></td>
			<td><?php echo $this->escapeHtml($row->getResource()); ?></td>
			<td><?php echo $this->escapeHtml($row->isVisible()); ?></td>
			<td>
				<?=$this->partial('uthando-admin/partial/edit-actions', [
                	'pk'		=> 'menuItemId',
                	'id'		=> $row->getMenuItemId(),
		    		'tableName'	=> 'menuItem',
                	'route'		=> 'admin/menu-item/edit',
				    'routeParams' => ['menuId' => $this->menuId],
		    	]);?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<?=$this->paginationControl(
    $this->models,
    'Elastic',
    'application/partial/paginate',
	[
        'route' => 'admin/menu-item/page',
        'routeParams' => ['menuId' => $this->menuId]
    ]
); ?>

<?php else: ?>
<h4>No menu items where returned by search.</h4>
<?php endif; ?>

