<?php $this->headTitle('Pages') ?>
<?=$this->ztbFlashMessenger()->render();?>

<a href="<?=$this->url('admin/page', [
		'menuId' => $this->menuId,
		'action' => 'add',
	]); ?>" class="btn">Add Page</a>
<div class="clear">&nbsp;</div>


<table class="table table-hover table-bordered table-condensed">
	<thead>
		<tr>
			<th data-field="pageId">Page Id</th>
			<th data-field="label">Label</th>
			<th data-field="params">Params</th>
			<th data-field="route">Route</th>
			<th data-field="reource">Resource</th>
			<th data-field="isVisible">Is Visible</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<?php if ($this->pages->count()): ?>
		<?php foreach($this->pages as $key => $row): ?>
		<tr>
			<td><?php echo $this->escapeHtml($row->getPageId()); ?></td>
			<td>
                <?php echo str_repeat('&nbsp;&nbsp;', ($row->getDepth())) . '&bull;&nbsp;'; ?>
                <?php echo $this->escapeHtml($row->getLabel()); ?></td>
			<td><?php echo $this->escapeHtml($row->getParams()); ?></td>
			<td><?php echo $this->escapeHtml($row->getRoute()); ?></td>
			<td><?php echo $this->escapeHtml($row->getResource()); ?></td>
			<td><?php echo $this->escapeHtml($row->isVisible()); ?></td>
			<td>
				<a href="<?=$this->basepath(
					'/admin/page/edit/id/' . $this->escapeHtml($row->getPageId())
				);?>" class="btn">Edit</a>
				&nbsp;
				
				<!-- Button to trigger modal -->
                <a href="#pageModel<?=$row->getPageId(); ?>" class="btn btn-danger" data-toggle="modal">Delete</a>
                <!-- Modal -->
				<div class="modal hide fade" id="pageModel<?=$row->getPageId();?>" tabindex="-1">
				  <div class="modal-header">
				    <button type="button" class="close" data-dismiss="modal">&times;</button>
				    <h3 id="pageModel<?=$row->getPageId(); ?>Label">Warning</h3>
				  </div>
				  <form class="form-horizontal"  method="post" action="<?=$this->url('admin/page', [
				        'action' => 'delete',
				    ]);?>">
				        <div class="modal-body">
				            <p>Are you sure you want to delete this page.</p>
				            <p class="label label-important">This action cannot be undone</p>
				        </div>
				        <input type="hidden" name="pageId" value="<?=$row->getPageId();?>">
				        <input type="hidden" name="menuId" value="<?=$row->getMenuId();?>">
				        <div class="modal-footer">
				            <button type="button" class="btn btn-primary" data-dismiss="modal">No Don't Do It</button>
				            <button type="submit" name="submit" class="btn btn-danger" value="delete">Yes Delete It</button>
				        </div>
				    </form>
				</div>
			</td>
		</tr>
		<?php endforeach; ?>
		<?php else: ?>
		<tr>
			<td colspan="3">No Pages Availible</td>
		</tr>
		<?php endif; ?>
	</tbody>
</table>

