<?php
$form = $this->form;
$routeArray = ['action' => $this->formAction];
if (isset($this->menuId)) $routeArray['menuId'] = $this->menuId;
if (isset($this->pageId)) $routeArray['id'] = $this->pageId;

?>
<div>
    <form class="form form-horizontal"  method="post" action="<?=$this->url('admin/page', $routeArray);?>">
        <fieldset>
        <legend><?=ucwords($this->formAction);?> Page Form:</legend>
        <div class="row-fluid">
            <div class="span6">
                
                <?=$this->ztbFormElement($form->get('label')); ?>
                
                <?=$this->ztbFormElement($form->get('route')); ?>
                
                <?=$this->ztbFormElement($form->get('params')); ?>
                
                <?=$this->ztbFormElement($form->get('resource')); ?>
                
                <?=$this->ztbFormElement($form->get('visible')); ?>
            </div>
            <div class="span6">
       	        <?=$this->ztbFormElement($form->getPageSelect($this->menuId)); ?>
       	        <div class="control-group">
                    <div class="controls">
                   	    <label class="radio">
                            <input type="radio" name="menuInsertType" id="menuInsertType1" value="insert" checked>
                            insert after this page.
                        </label>
                        <label class="radio">
                            <input type="radio" name="menuInsertType" id="menuInsertType2" value="insertSub">
                            insert as a subpage of this page.
                        </label>
                    </div>
                </div>
            </div>
        </div>
        
       	<?=$this->formHidden($form->get('pageId'));?>
        <?=$this->formHidden($form->get('menuId')->setValue($this->menuId));?>
        <input type="hidden" name="action" value="<?=$this->formAction;?>">
        
        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn btn-primary" 
                data-loading-text="Please wait...">Submit</button>
                <button type="button" class="btn btn-warning" 
                data-loading-text="Please wait..." onClick="window.location = '<?=$this->url('admin/page', [
                        'action' => 'list',
                        'menuId' => $this->menuId
                    ]);?>';">Cancel</button>
            </div>
        </div>
        </fieldset>
    </form>
</div>
