<?php $this->headTitle('Add Menu') ?>
<?php $this->layout()->pageTitle = $this->translate('Add Menu');?>

<?php $this->placeholder('header-buttons')->captureStart();?>
<button type="submit" form="form-menu" data-toggle="tooltip" title="<?=$this->translate('Save');?>" class="btn btn-primary">
    <i class="fa fa-save"></i>
</button>
<a href="<?=$this->url('admin/menu');?>" data-toggle="tooltip" title="<?=$this->translate('Cancel');?>" class="btn btn-default">
    <i class="fa fa-reply"></i>
</a>
<?php $this->placeholder('header-buttons')->captureEnd();?>

<?php

$this->form->setAttributes([
    'method' => 'post',
    'id' => 'form-menu',
    'action' => $this->url('admin/menu/edit', [
        'action' => 'add',
    ]),
]);

?>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><i class="fa fa-pencil"></i> <?=$this->translate('Add Menu');?></h3>
    </div>
    <div class="panel-body">
        <?=$this->form($this->form);?>
    </div>
</div>
