<?= $this->partial('uthando-admin/partial/search', [
    'name' => 'menu',
    'searchInputs' => [
        'Menu' => 'menu',
    ],
]); ?>

<div id="table-menu">
    <?= $this->partial('uthando-navigation/menu/list', [
        'models' => $this->models
    ]); ?>
</div>


<script>
    $(document).ready(function() {
        $('#table-menu').dataGrid({
            url: 'menu/list',
            query: {sort: 'menu'},
            searchForm: $('#search-menu'),
            paging: 'links',
            columnSort: true
        });
    });
</script>
