<?php $this->headTitle('Menus') ?>

<table class="table table-hover table-bordered table-condensed">
	<thead>
		<tr>
			<th data-field="menuId">Menu Id</th>
			<th data-field="title">Menu</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->menus as $row): ?>
		<tr>
			<td><?=$this->escapeHtml($row->getMenuId()); ?></td>
			<td><?=$this->escapeHtml($row->getMenu()); ?></td>
			<td>
				<a href="<?=$this->basepath(
					'/admin/menu/edit/id/' . $this->escapeHtml($row->getMenuId())
				);?>" class="btn">Edit</a>
				&nbsp;
				
				<a href="<?=$this->basepath(
					'/admin/page/list/menuId/' . $this->escapeHtml($row->getMenuId())
				);?>" class="btn">Edit Pages</a>
				&nbsp;
				
				<!-- Button to trigger modal -->
                <a href="#menuModel<?=$row->getMenuId();?>" class="btn btn-danger" data-toggle="modal">Delete</a>
                <!-- Modal -->
				<div class="modal hide fade" id="menuModel<?=$row->getMenuId();?>" tabindex="-1">
				  <div class="modal-header">
				    <button type="button" class="close" data-dismiss="modal">&times;</button>
				    <h3 id="menuModel<?=$row->getMenuId();?>Label">Warning</h3>
				  </div>
				  <form class="form-horizontal"  method="post" action="<?=$this->url('admin/menu', array(
				        'action' => 'delete',
				    ));?>">
				        <div class="modal-body">
				            <p>Are you sure you want to delete this menu.</p>
				            <p class="label label-important">This action cannot be undone</p>
				        </div>
				        <input type="hidden" name="menuId" value="<?=$row->getMenuId();?>">
				        <div class="modal-footer">
				            <button type="button" class="btn btn-primary" data-dismiss="modal">No Don't Do It</button>
				            <button type="submit" name="submit" class="btn btn-danger" value="delete">Yes Delete It</button>
				        </div>
				    </form>
				</div>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
