<?php $this->headTitle('Menus') ?>

<?php if (count($this->models) > 0): ?>

<table class="table table-hover table-bordered table-condensed">
	<thead>
		<tr>
			<th data-field="menuId">Menu Id</th>
			<th data-field="title">Menu</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->models as $row): ?>
		<tr>
            <td><?=$this->escapeHtml($row->getMenuId()); ?></td>
			<td><?=$this->escapeHtml($row->getMenu()); ?></td>
			<td>
				
				<a href="<?=$this->url('admin/menu-item', [
                    'menuId' => $row->getMenuId(),
				]);?>" class="btn">Edit Pages</a>
				&nbsp;
				
				<?=$this->partial('uthando-admin/partial/edit-actions', [
                	'pk'		=> 'menuId',
                	'id'		=> $row->getMenuId(),
		    		'tableName'	=> 'menu',
                	'route'		=> 'admin/menu/edit',
		    	]);?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<?=$this->paginationControl(
    $this->models,
    'Elastic',
    'application/partial/paginate',
	['route' => 'admin/menu/page']
); ?>

<?php else: ?>
<h4>No menus where returned by search.</h4>
<?php endif; ?>
